# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_swapcontract_contract_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapcontract',
            name='contract_flag',
            field=models.IntegerField(default=0),
        ),
    ]
