# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0006_swapcontract_contract_add_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SwapDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_name', models.CharField(max_length=500)),
                ('swap_sector', models.CharField(max_length=200)),
                ('swap_counter_party', models.IntegerField(default=0)),
                ('swap_margin', models.IntegerField()),
                ('swap_base_curr', models.CharField(choices=[('USD', 'USD'), ('GBR', 'GBR'), ('JYP', 'JYP')], default=None, max_length=50)),
                ('swap_trade_curr', models.CharField(blank=True, choices=[('USD', 'USD'), ('GBR', 'GBR'), ('JYP', 'JYP')], max_length=50)),
                ('swap_status_request', models.IntegerField(default=0)),
                ('swap_status_accept', models.IntegerField(default=0)),
                ('swap_start_date', models.DateField()),
                ('swap_end_date', models.DateField()),
                ('swap_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
